#!/usr/bin/env bash
# Generate an Argo CD Application for ai-o11y-demo-apps from .env.
#
# Why this exists: install.sh writes a gitignored .helm-values-overrides.yaml
# and runs `helm upgrade` imperatively. The GitOps equivalent is an Argo CD
# Application whose Helm values carry the same secrets — but those secrets must
# not be committed. This script reads the SAME .env install.sh uses and inlines
# the values as spec.source.helm.valuesObject, writing a gitignored file you
# apply by hand:
#
#     ./tools/generate-argocd-app.sh
#     kubectl apply -f argocd/application.generated.yaml
#
# Two GitOps-specific differences from install.sh (both deliberate):
#   1. postgres.password is set EXPLICITLY. Argo CD renders via `helm template`,
#      where the chart's `lookup`-based password persistence returns empty, so
#      randAlphaNum would re-roll on every sync and break postgres-0 auth. We
#      generate the password once and persist it to .env (POSTGRES_PASSWORD).
#   2. The chart is pulled from git (repoURL/targetRevision/path). The synthetic
#      user pool (helm/config/users.yaml) is gitignored, so it must be committed
#      to the targetRevision or loadgen comes up with an empty pool. See README.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
OUT_DIR="${REPO_ROOT}/argocd"
OUT_FILE="${OUT_DIR}/application.generated.yaml"

say()  { printf '%s\n' "$*"; }
ok()   { printf '  [OK] %s\n' "$*"; }
die()  { printf '  [ERROR] %s\n' "$*" >&2; exit 1; }

# ── GitOps source (override via env before running if you use a fork) ─────────
ARGOCD_REPO_URL="${ARGOCD_REPO_URL:-https://github.com/mwimpelberg28/ai-o11y-demo-apps}"
ARGOCD_TARGET_REVISION="${ARGOCD_TARGET_REVISION:-feat/eks-terraform-argocd}"
ARGOCD_PATH="${ARGOCD_PATH:-helm}"
ARGOCD_DEST_SERVER="${ARGOCD_DEST_SERVER:-https://kubernetes.default.svc}"
ARGOCD_APP_NAMESPACE="${ARGOCD_APP_NAMESPACE:-argocd}"

[[ -f "$ENV_FILE" ]] || die "No .env found at ${ENV_FILE}. Run ./tools/install.sh first (or create .env)."
# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

# ── Required values ──────────────────────────────────────────────────────────
: "${CLAUDE_API_KEY:?CLAUDE_API_KEY missing from .env}"
: "${SIGIL_ENDPOINT:?SIGIL_ENDPOINT missing from .env}"
: "${SIGIL_AUTH_TENANT_ID:?SIGIL_AUTH_TENANT_ID missing from .env}"
: "${SIGIL_AUTH_TOKEN:?SIGIL_AUTH_TOKEN missing from .env}"
: "${OTEL_EXPORTER_OTLP_ENDPOINT:?OTEL_EXPORTER_OTLP_ENDPOINT missing from .env}"

# OTEL headers: prefer the precomputed value install.sh wrote; otherwise build
# it from instance id + token (same formula as install.sh compute_otel_headers).
if [[ -z "${OTEL_EXPORTER_OTLP_HEADERS:-}" ]]; then
  : "${OTEL_OTLP_INSTANCE_ID:?OTEL_OTLP_INSTANCE_ID missing and OTEL_EXPORTER_OTLP_HEADERS not set}"
  : "${OTEL_OTLP_TOKEN:?OTEL_OTLP_TOKEN missing and OTEL_EXPORTER_OTLP_HEADERS not set}"
  _b64=$(printf '%s' "${OTEL_OTLP_INSTANCE_ID}:${OTEL_OTLP_TOKEN}" | base64 | tr -d '\n')
  OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic ${_b64}"
fi

# ── Stable Postgres password (persisted to .env; see header note) ────────────
if [[ -z "${POSTGRES_PASSWORD:-}" ]]; then
  # Read a fixed block of random bytes, then slice in bash — piping into
  # `head -c` would close the pipe early and trip `set -o pipefail`.
  _rand="$(head -c 1024 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9')"
  POSTGRES_PASSWORD="${_rand:0:24}"
  printf '\n# ── Postgres (generated by generate-argocd-app.sh; stable across Argo syncs) ──\nPOSTGRES_PASSWORD="%s"\n' "$POSTGRES_PASSWORD" >> "$ENV_FILE"
  ok "Generated POSTGRES_PASSWORD and appended to .env"
fi

POSTGRES_DATABASE="${POSTGRES_DATABASE:-aio11y}"
POSTGRES_USER="${POSTGRES_USER:-aio11y}"

mkdir -p "$OUT_DIR"

# ── Emit the Application ──────────────────────────────────────────────────────
# valuesObject mirrors install.sh's .helm-values-overrides.yaml, plus an
# explicit postgres block. Indentation: valuesObject children sit at 8 spaces.
{
cat <<EOF
# Auto-generated by tools/generate-argocd-app.sh — DO NOT commit. Gitignored.
# Contains secrets. Regenerate by re-running the script.
#
#   kubectl apply -f argocd/application.generated.yaml
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-o11y-demo-apps
  namespace: ${ARGOCD_APP_NAMESPACE}
  # Keep the apps around if the Application is deleted accidentally; remove to
  # allow cascading delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${ARGOCD_REPO_URL}
    targetRevision: ${ARGOCD_TARGET_REVISION}
    path: ${ARGOCD_PATH}
    helm:
      # Chart's own values.yaml is the base; these override it (same as
      # \`helm upgrade --values values.yaml --values <override>\`).
      valuesObject:
        global:
          anthropic:
            apiKey: "${CLAUDE_API_KEY}"
          openai:
            apiKey: "${OPENAI_API_KEY:-}"
          gemini:
            apiKey: "${GEMINI_API_KEY:-}"
          ollama:
            baseUrl: "${OLLAMA_BASE_URL:-}"
          sigil:
            endpoint: "${SIGIL_ENDPOINT}"
            protocol: "${SIGIL_PROTOCOL:-http}"
            authMode: "${SIGIL_AUTH_MODE:-basic}"
            tenantId: "${SIGIL_AUTH_TENANT_ID}"
            token: "${SIGIL_AUTH_TOKEN}"
          otel:
            endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
            headers: "${OTEL_EXPORTER_OTLP_HEADERS}"
          grafana:
            url: "${GRAFANA_URL:-}"
          caps:
            anthropic:
              usdPerDay: ${ANTHROPIC_CAP_USD_PER_DAY:-30}
EOF

# providerWeights only when set (mirror install.sh: don't clobber chart default)
if [[ -n "${PROVIDER_WEIGHTS:-}" ]]; then
  printf '          providerWeights: "%s"\n' "${PROVIDER_WEIGHTS}"
fi

# Explicit postgres block — REQUIRED under Argo (see header note on lookup).
cat <<EOF
        postgres:
          database: "${POSTGRES_DATABASE}"
          user: "${POSTGRES_USER}"
          password: "${POSTGRES_PASSWORD}"
        loadgen:
          ncTotalUsers: ${NC_TOTAL_USERS:-200}
          ncAiAdoptionRate: ${NC_AI_ADOPTION_RATE:-0.25}
          sbTotalUsers: ${SB_TOTAL_USERS:-30}
EOF

# Optional Ingress (mirror install.sh)
if [[ -n "${INGRESS_NEONCART_HOST:-}" || -n "${INGRESS_SUPPORTBOT_HOST:-}" ]]; then
cat <<EOF
        ingress:
          enabled: true
          className: "${INGRESS_CLASS_NAME:-}"
          neoncart:
            host: "${INGRESS_NEONCART_HOST:-}"
          supportbot:
            host: "${INGRESS_SUPPORTBOT_HOST:-}"
EOF
fi

# Destination + sync policy. The chart hardcodes its own namespaces, so the
# destination namespace is only a fallback for unscoped resources.
cat <<EOF
  destination:
    server: ${ARGOCD_DEST_SERVER}
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Chart manages its own namespaces (templates/namespaces.yaml).
      - CreateNamespace=false
      # Server-side apply avoids "metadata.annotations too long" on big CRDs/CMs.
      - ServerSideApply=true
EOF
} > "$OUT_FILE"

chmod 600 "$OUT_FILE"
ok "Wrote ${OUT_FILE} (chmod 600, gitignored)"
say ""
say "Next:"
say "  1. Ensure the user pool is committed to ${ARGOCD_REPO_URL}@${ARGOCD_TARGET_REVISION}:"
say "       git add -f helm/config/users.yaml && git commit && git push"
say "     (gitignored by default — without it loadgen runs with an empty pool)."
say "  2. Apply the Application:"
say "       kubectl apply -f ${OUT_FILE}"
say "  3. Watch it sync:"
say "       kubectl -n ${ARGOCD_APP_NAMESPACE} get application ai-o11y-demo-apps -w"
